/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testAppMessage() {
        assertEquals(message(), "Advent of code 2019")
    }
}
